### ISSUE TITLE
How to delete YT feed

### ISSUE THREAD

**Issue by alfonder** [umputun/feed-master#105]
Not really an issue, rather a request.
If I don't want to process a youtube channel, then removing it from the config is not enough as I noted. All already converted files remain on the storage. And also I guess DB entries are not deleted.
So I think I should use admin API. But it's unclear how to do it. Is it possible to delete all channel's entries with a mask? Otherwise where to get entry ids?
For example, here is the snippet from rss:
```
<item>
<title>
Екатерина Шульман: Безумно богатые русские. От олигархов к новой буржуазии / Книжное казино. Истории // 07.01.2023
</title>
<link>https://www.youtube.com/watch?v=QqfVcDEgDS8</link>
<description>
В первом в этом году выпуске программы... 
</description>
<enclosure url="https://feed.myserver.xx/yt/media/8c390919daa769e308eac77f4d60cfcbf90bab87.mp3" length="64355071" type="audio/mpeg"/>
<guid>UCuIE7-5QzeAR6EdZXwDRwuQ::QqfVcDEgDS8</guid>
<pubDate>Sat, 07 Jan 2023 12:04:37 +0000</pubDate>
<author>Дилетант</author>
<itunes:duration>3273</itunes:duration>
</item>
```
I tried to use curl as following:
```
curl -X "DELETE" -u admin:mycoolpass --basic  http://feed.myserver.xx/yt/entry/UCuIE7-5QzeAR6EdZXwDRwuQ/QqfVcDEgDS8
```
And I get "301 Moved Permanently"
Also either ID from mp3 filename or ID from YT video don't work. The same error returned.
Please, explain me how to perform deletion.

**Comment by umputun** [comment]
regarding "Otherwise where to get entry ids?" it looks like you have figured it -  you can get both channel and video IDs from the RSS, as it build like this: `GUID: entry.ChannelID + "::" + entry.VideoID`

**Comment by alfonder** [comment]
Thank you. It works via un-proxied connection.
```
{"removed":"QqfVcDEgDS8","status":"ok"}
```
