### ISSUE TITLE
Add ability to publish to telegram

### ISSUE THREAD

**Issue by umputun** [umputun/feed-master#13]
The idea is to use telegram as an optional destination for any given feed.

**Comment by umputun** [comment]
note: https://core.telegram.org/bots/api#sendaudio

An audio file is limited to 50M. There are a few ways to deal with this:

- detect file size and if above 50m post a link
- always publish links (to mp3) only
- figure a way to publish large files directly to telegram and link them

**Comment by imaxmelnyk** [comment]
I see this as a telegram bot subscribes for RSS feed and post it to the channel, there are tons of such bots tho.. Am I wrong? What do you have in mind?

**Comment by umputun** [comment]
> Am I wrong? What do you have in mind?

I have in mind not just publishing RSS item but retrieving an enclosed file and publishing mp3 to telegram as well, if possible. I think my comment above describes it clear enough.

**Comment by sgaynetdinov** [comment]
[Telegram боты. Загружаем файлы больше 50мб] (https://habr.com/ru/post/348234/)
