### ISSUE TITLE
Don't process ongoing YT live streams

### ISSUE THREAD

**Issue by alfonder** [umputun/feed-master#137]
Previously that was not the case. At least I didn't face it for 2 years of usage.
Observed behavior:
When YT scanner encounters a new video during the regular checking, and the video is longer than defined minimum length, it starts downloading-and-converting the video. Even if that video is an ongoing live stream. The result is a number of unfinished episodes in the feed.
Expected behavior:
The YT scanner should skip live streams when they're in progress. Then on the next run if the stream is finished it would be processed completely.
Additional comment:
I don't know if there's any property which could indicate such type of videos. I hope it's possible technically.

**Comment by orthur** [comment]
it can be done with yt-dlp parameter `--match-filter !is_live'

**Comment by alfonder** [comment]
OK, thanks. So it's possible. Now the task is to implement this in feed-master.

**Comment by orthur** [comment]
yt-dlp parameters can be set in feed-master yaml config in section `youtube`
 https://github.com/umputun/feed-master/blob/f22f5139c39a42241561fb6041e98727ef509123/yt-test.yml#L22

**Comment by alfonder** [comment]
Solved
