### ISSUE TITLE
Post is present on echo.feed-master.com but absent on @echomsk_u

### ISSUE THREAD

**Issue by pavelseverov** [umputun/feed-master#140]
Hi!
The below post (visible on https://echo.feed-master.com/) is absent on @echomsk_u.
_"Живой Гвоздь: Статус. Екатерина Шульман* и Максим Курников / 10.12.2024 @Ekaterina_Schulmann"._
Probably because it is marked as "Junk", see the attached screenshot.

Thank you for your work! :-)

![2024-12-12 17_49_53-Feed Master and 10 more pages - Work - Microsoft​ Edge](https://github.com/user-attachments/assets/0b3069c6-bfec-435e-ba6a-8a35da5c57c5)

**Comment by umputun** [comment]
this is intentional, not a bug but rather the configuration settings intending to filter double-posting of the episode presented in other channels. I'm not sure if this still a case now, but as I configured it "Статус" was presented in both "Живой Гвоздь" and in her personal video blog

**Comment by umputun** [comment]
this is from her channel, which is included in the feed

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/eb54a636-d0fc-4a61-849d-676eb7b7454a" />

the same episode published by "Живой Гвоздь" skipped (and always was) to avoid dups
