### ISSUE TITLE
Make a better mobile version 

### ISSUE THREAD

**Issue by umputun** [umputun/feed-master#5]
Currently, the feed web-view looks ok on [the desktop](http://feedmaster.umputun.com/feed/echo-msk), but not that nice on a mobile screen.

**Comment by k2fx** [comment]
The <meta name="viewport" content="width=device-width, initial-scale=1"> should be added to the head section 
app/webapp/templates/feed.tmpl

**Comment by umputun** [comment]
@k2fx  I'm not sure how this supposed to help, but it still as ugly as before.

**Comment by k2fx** [comment]
@umputun It helped. Now it could be responsive. Next, we need to edit  CSS and replace table-based HTML mark up with divs markup. I'll send code in half an hour.

**Comment by umputun** [comment]
thx. could you make it PR?

**Comment by k2fx** [comment]
what does it mean PR?

**Comment by umputun** [comment]
[Pool request](https://help.github.com/en/articles/about-pull-requests)

**Comment by k2fx** [comment]
` <style>
        .ump-feed-master-header {
            width: 100%;
            padding: .75rem 1rem;
            font-size: 1.25rem;
            border-bottom: 1px solid #000;
        }
        .ump-feed-master-header__brand {
            display: flex;
        }
        .ump-feed-master-header__meta {
            margin-left: calc(38px + 1rem);
            margin-top: 0.275rem;
            display: flex;
            color: rgba(0, 0, 0, 0.35);
            font-size: 0.875rem;
        }
        @media (min-width: 760px) {
            .ump-feed-master-header__meta {
                margin-left: calc(58px + 1rem);
            }
        }
        @media (min-width: 1240px) {
            .ump-feed-master-header {
                display: flex;
            }
            .ump-feed-master-header__brand {
                align-items: center;
            }
            .ump-feed-master-header__meta{
                margin-left: auto;
                margin-top: 0;
                display: flex;
                align-items: center;
                font-size: 1rem;
            }
        }
        .ump-feed-master-logo {
            width: 38px;
            height: 38px;
            display: block;
            margin-right: 1rem;
        }
        @media (min-width: 760px) {
            .ump-feed-master-logo {
                width: 58px;
                height: 58px;
            }
        }

        .ump-feed-master-name {
            font-weight: bold;
            display: block;
            font-size: 1.25rem;
            white-space: nowrap;
            padding-bottom: 0.125em;
        }
        .ump-feed-master-info {
            font-size: 1rem;
        }
        .ump-feed-master-header-link {
            color: inherit;
            text-decoration: none;
            display: inline-block;
            padding: 4px 0;
            border-bottom: 1px dotted #999;
        }
        .ump-feed-master__data-row {
            display: flex;
            padding: 1rem;
            font-size: 1rem;
            border-bottom: 1px solid rgba(0, 0, 0, 0.3);
        }
        .ump-feed-master__data-row-player-cell {
            width: 38px;
            text-align: center;
        }
        @media (min-width: 760px) {
            .ump-feed-master__data-row-player-cell {
                width: 58px;
            }
        }
        .ump-feed-master__data-row-info-cell {
            flex: 1;
            padding-left: 0.75rem;
        }
        .ump-feed-master-timestamp-cell {
            margin-left: auto;
            color: rgba(0, 0, 0, 0.35);
            padding-top: 0.5rem;
            font-size: .825rem;
        }
        @media (min-width: 1240px) {
            .ump-feed-master__data-row-info-cell {
                display: flex;
            }
            .ump-feed-master-timestamp-cell {
                padding-top: 0;
                font-size: 1rem;
            }
        }
        .ump-feed-master-footer {
            font-size: .825rem;
            text-align: center;
            padding: 1rem;
            background: rgba(0, 0, 0, 0.2);
        }
        .fa-volume-up {
            color: inherit;
        }
    </style>`

**Comment by k2fx** [comment]
New styles

` .ump-feed-master-header {
            width: 100%;
            padding: .75rem 1rem;
            font-size: 1.25rem;
            border-bottom: 1px solid #000;
        }
        .ump-feed-master-header__brand {
            display: flex;
        }
        .ump-feed-master-header__meta {
            margin-left: calc(38px + 1rem);
            margin-top: 0.275rem;
            display: flex;
            color: rgba(0, 0, 0, 0.35);
            font-size: 0.875rem;
        }
        @media (min-width: 760px) {
            .ump-feed-master-header__meta {
                margin-left: calc(58px + 1rem);
            }
        }
        @media (min-width: 1240px) {
            .ump-feed-master-header {
                display: flex;
            }
            .ump-feed-master-header__brand {
                align-items: center;
            }
            .ump-feed-master-header__meta{
                margin-left: auto;
                margin-top: 0;
                display: flex;
                align-items: center;
                font-size: 1rem;
            }
        }
        .ump-feed-master-logo {
            width: 38px;
            height: 38px;
            display: block;
            margin-right: 1rem;
        }
        @media (min-width: 760px) {
            .ump-feed-master-logo {
                width: 58px;
                height: 58px;
            }
        }

        .ump-feed-master-name {
            font-weight: bold;
            display: block;
            font-size: 1.25rem;
            white-space: nowrap;
            padding-bottom: 0.125em;
        }
        .ump-feed-master-info {
            font-size: 1rem;
        }
        .ump-feed-master-header-link {
            color: inherit;
            text-decoration: none;
            display: inline-block;
            padding: 4px 0;
            border-bottom: 1px dotted #999;
        }
        .ump-feed-master__data-row {
            display: flex;
            padding: 1rem;
            font-size: 1rem;
            border-bottom: 1px solid rgba(0, 0, 0, 0.3);
        }
        .ump-feed-master__data-row-player-cell {
            width: 38px;
            text-align: center;
        }
        @media (min-width: 760px) {
            .ump-feed-master__data-row-player-cell {
                width: 58px;
            }
        }
        .ump-feed-master__data-row-info-cell {
            flex: 1;
            padding-left: 0.75rem;
        }
        .ump-feed-master-timestamp-cell {
            margin-left: auto;
            color: rgba(0, 0, 0, 0.35);
            padding-top: 0.5rem;
            font-size: .825rem;
        }
        @media (min-width: 1240px) {
            .ump-feed-master__data-row-info-cell {
                display: flex;
            }
            .ump-feed-master-timestamp-cell {
                padding-top: 0;
                font-size: 1rem;
            }
        }
        .ump-feed-master-footer {
            font-size: .825rem;
            text-align: center;
            padding: 1rem;
            background: rgba(0, 0, 0, 0.2);
        }
        .fa-volume-up {
            color: inherit;
        }`

**Comment by Menma27** [comment]
@k2fx Are you going to finish this issue later or don't have time for this?
