### ISSUE TITLE
Maybe use kkdai/youtube

### ISSUE THREAD

**Issue by orthur** [umputun/feed-master#59]
@umputun what do you think if to use https://github.com/kkdai/youtube/ written in Go instead of yt-dlp?

**Comment by umputun** [comment]
the reason I use yt-dlp is very simple - it works and works fast. The suggested thingy seems to have the same problem with the slow download as youtube-dl. In addition,  yt-dlp also provides a simple way of extracting audio.

the bottom line - I don't see a reason to switch,  yt-dlp works fast, reliably, and seems to be actively maintained by a large community.

**Comment by orthur** [comment]
Got it, case closed
