### ISSUE TITLE
Add UI page for the list of source RSS feeds

### ISSUE THREAD

**Issue by umputun** [umputun/feed-master#60]
The goal is to be able to go from the feed page to the list of feed. Visually we can just add a link here to navigate to the list

<img width="583" alt="q46kx-202203-27141117-o5lyn" src="https://user-images.githubusercontent.com/535880/160296890-2d25d2e7-b13e-4a4b-b20e-66326d24aabc.png">

Each row in this list should include the title (with rss-link), number or entries and the last pudate

@orthur - this one is very similar to #58 you have added. Let me know if you want to take it too

**Comment by orthur** [comment]
Sure I take it

**Comment by umputun** [comment]
looking good, thx
