### ISSUE TITLE
Add duration field to items

### ISSUE THREAD

**Issue by lomax** [umputun/feed-master#68]
According to the Google documentation on RSS feeds supported by Google Podcasts platform https://support.google.com/podcast-publishers/answer/9889544?hl=ru#recommended_episode there is an extended `<itunes:duration>` attribute. Given it's name it should be supported by Apple too.

It's very convenient to have episode duration shown in the app interface for each item of the feed.

**Comment by umputun** [comment]
I have added duration to youtube-based items and pass-through for the regular items, coming from podasts' RSS feeds. The change in master

**Comment by lomax** [comment]
Thank you, duration of an episode now shown in Google Podcasts.
