### ISSUE TITLE
ERROR: [youtube] M3GgCZFVBIo: Sign in to confirm your age. This video may be inappropriate for some users

### ISSUE THREAD

**Issue by umputun** [umputun/feed-master#72]
I have seen this message and it failed to download. Not a big deal but maybe there is a magical key for yt-dlp to allow such videos to get processed

**Comment by paskal** [comment]
Problem was mentioned [on reddit](https://www.reddit.com/r/youtubedl/comments/qpdp0q/comment/i2pyrvv/?utm_source=reddit&utm_medium=web2x&context=3) also.

**Comment by umputun** [comment]
well, i guess it is what it is. Will close
