### ISSUE TITLE
Private feed-master server and iOS client

### ISSUE THREAD

**Issue by aplsms** [umputun/feed-master#73]
Hello,

I'm not sure that's server issue.
i have private feed-master server  in my network. i can open feeds and play episodes from browser. But i can't add feed to the podcasts.app on my iPhone. Looks like public access required for some apple servers.

Browser hits:

`2022/04/07 20:50:02.868 [INFO]  {logger/logger.go:134} GET - /feed/ap-yt - feeds.local - unknown ip - 200 (37174) - 1.015642ms`

But there is no hits if i'm trying add podcast to the podcasts.app

Do you know application that allows to download podcasts from private server?

Thank you.

**Comment by umputun** [comment]
I have tried this too. It worked fine on both Podcast clients (mac and iPhone versions) however doesn’t work with overcast. As far as I recall overcast is doing some kind of local retrieval for their web client and probably they are trying to reach from the outside.

All I did is put both server and client on the same LAN and add the feed by URL as `http://192.168.1.39:8080/rss/yt-example` (192.168.1.39 is my server's IP)

You may check if any firewall is turned on on your server and also make sure iphone's "hide my ip" off for the local wifi

**Comment by aplsms** [comment]
fixed. it was issue in configuration.
