### ISSUE TITLE
Add MP3 tags

### ISSUE THREAD

**Issue by pavelseverov** [umputun/feed-master#79]
Could you please add tag(s) to MP3 files. Like:
- ID of the source (e.g. "plushev")
- Timestamp (e.g. "2022-04-18 11:40")
- Name of the broadcast (e.g. "Breakfast Show. Срочники на 'Москве'")
- etc
If it will be combined in the single tag - then better to divide this "fields" with something special, to allow further automatic processing.
Thanks in advance! :-)

**Comment by umputun** [comment]
> It it will be combined in the single tag

why? mp3 files have common tags and I don't understand why would we combine them into our own

**Comment by umputun** [comment]
added mp3 tags to files downloaded from yt

**Comment by umputun** [comment]
I think this one can be closed. Let me know if all good with this change.

**Comment by pavelseverov** [comment]
@umputun, thank you!
Can you save complete date-time? Or at least complete date? Currently it is only year: **"Recorded date: 2022"**

**Comment by umputun** [comment]
I'm saving the year, because this is the "Year" tag https://github.com/umputun/feed-master/blob/master/app/youtube/service.go#L477

In theory, I can store a full date-time in some custom tag, like "DateTime" bur I have no clue if this is a common practice and or what the proper tag for this

**Comment by umputun** [comment]
I think I have found a tag for this. In V24 it is `TDRC` (Recording time). The only app i have to deal with tags is mac's Tag (probably some old version) and it shows the tag like this:
<img width="858" alt="6y5p5-202204-20033258-fpoa7" src="https://user-images.githubusercontent.com/535880/164186693-333aebad-80a7-4d56-9f66-bac0e36dbcc1.png">

**Comment by umputun** [comment]
you good with this? if so, pls close

**Comment by pavelseverov** [comment]
Yes, that's great! Thank you! :-)

**Comment by pavelseverov** [comment]
👍
